version: "3.8"

services:
  api:
    build: .
    container_name: "rest-api"
    environment:
      TEST: "test"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      DB_NAME: "mydb"
      DB_HOST: "host.docker.internal"
      DB_PORT: "26257"
    ports:
      - "8000:8000"
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
